Add music and videos
publiccodenet/brand pull request #14
Opened 2020-08-12 09:57 UTC by Ainali

Fixes #13 and is also part of the solution for https://github.com/publiccodenet/bumperscripter/issues/12

2020-08-12 10:25 UTC, felixfaassen reviewed
@Ainali no blocker for me but would be nice to add the license for the music as well.

2020-08-12 10:38 UTC, Ainali commented
> @Ainali no blocker for me but would be nice to add the license for the music as well.

I believe that the files here in Brand are not freely licensed at all, they are just "© Foundation for Public Code, 2018" per the readme (where the year should perhaps be updated).

2020-09-11 08:26 UTC, felixfaassen reviewed
@Ainali great work organizing the media files. One thought I have is to maybe add a AUTHORS.md file. Reason I bring it up is that I am always sensitive about my music. I have no problems putting out in the world but it would me nice to have a place of attribution of authors artwork just as we have an authors file for the standard.

2020-09-24 10:53 UTC, bvhme requested changes
Very good, ony minor piece of documentation that needs improvement.

2020-09-24 10:53 UTC, bvhme commented on video/readme.md
> +Here are some music files that are meant to reinforce the philosophy of the brand.
I'm guessing this is copy-pasted, but these aren't `music`

2020-10-05 09:15 UTC, Ainali commented
> @Ainali great work organizing the media files. One thought I have is to maybe add a AUTHORS.md file. Reason I bring it up is that I am always sensitive about my music. I have no problems putting out in the world but it would me nice to have a place of attribution of authors artwork just as we have an authors file for the standard.

@felixfaassen  Yes, that's reasonable. Should we make that a separate PR since there will be other authors in that list not related to these files?

2020-10-05 10:04 UTC, felixfaassen commented
> > @Ainali . Excellent idea let's make a separate pull request for that

2020-10-20 13:37 UTC, bvhme approved these changes
Great, I'm guessing the video and audio also needs to be versioned.

2020-10-20 14:21 UTC, merged